### ISSUE TITLE
Is there any example project?

### ISSUE THREAD

**Issue by RdeWilde** [cl3m/multiplatform-compose#1]
Can I somewhere find an example project implementing this multiplatform-compose?

**Comment by cl3m** [comment]
The library is not released yet but you can clone or download the whole repository and start the androidApp from Android Studio or the iosApp from Xcode. It is like a normal kotlin multi platform mobile project.

**Comment by RdeWilde** [comment]
Any clue on the dependencies I need to install? @cl3m 

I guess at least Android Studio, Xcode and Cacoapods.

I got this error.

```
Caused by: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /usr/bin/xcrun command returned non-zero exit code: 72.
...
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':multiplatform-compose:cinteropYogaKitIosArm64'
...
at org.jetbrains.kotlin.compilerRunner.KotlinToolRunner.runViaExec(KotlinToolRunner.kt:77)
	at org.jetbrains.kotlin.compilerRunner.KotlinToolRunner.run(KotlinToolRunner.kt:73)
	at org.jetbrains.kotlin.gradle.tasks.CInteropProcess.processInterop(KotlinNativeTasks.kt:981)
...
```

**Comment by RdeWilde** [comment]
After doing all the regular stuff like installing xcode/ruby+gem/cocoapods and cocoapods-generate, it now seems to work.
